/*
 * Zephyr autoconf.h for MicroPython
 *
 * This file provides CONFIG_* defines expected by Zephyr headers and sources.
 * In Zephyr this is auto-generated by Kconfig, but we use static configuration.
 */

#ifndef ZEPHYR_AUTOCONF_H_
#define ZEPHYR_AUTOCONF_H_

// Include our static configuration
#include "../zephyr_ble_config.h"

// Net buffer configuration (required by net_buf.h)
#define CONFIG_NET_BUF 1
#define CONFIG_NET_BUF_LOG 0
#define CONFIG_NET_BUF_SIMPLE_LOG 0
#define CONFIG_NET_BUF_POOL_USAGE 0
#define CONFIG_NET_BUF_ALIGNMENT 0

// Assert configuration
#ifdef NDEBUG
#define CONFIG_ASSERT 0
#else
#define CONFIG_ASSERT 1
#endif

#define CONFIG_ASSERT_VERBOSE 1
#define CONFIG_ASSERT_LEVEL 2

// Test mode (disables device tree requirement in hci_core.c)
#define CONFIG_ZTEST 1

// Toolchain
#ifdef __GNUC__
#define CONFIG_TOOLCHAIN_GCC_VARIANT 1
#endif

#endif /* ZEPHYR_AUTOCONF_H_ */
