/*
 * Stub syscall_list.h for MicroPython Zephyr kernel integration
 *
 * The Zephyr kernel expects this file to be generated by the build system.
 * Since we're not using the full Zephyr build, we provide an empty stub.
 * Syscalls are not needed for basic kernel threading functionality.
 */

#ifndef ZEPHYR_INCLUDE_SYSCALL_LIST_H_
#define ZEPHYR_INCLUDE_SYSCALL_LIST_H_

// Empty stub - no syscalls defined

#endif /* ZEPHYR_INCLUDE_SYSCALL_LIST_H_ */
