freeze("$(PORT_DIR)/modules")
include("$(MPY_DIR)/extmod/asyncio", repl_asyncio=True)
require("onewire")
require("ds18x20")
require("dht")
require("usb-device")
require("usb-device-cdc")
require("usb-device-hid")
require("usb-device-keyboard")
require("usb-device-mouse")
