name: MCUboot

on:
  push:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
      - 'extmod/extmod.cmake'
      - 'extmod/extmod.mk'
      - 'extmod/modmcuboot.*'
      - 'lib/littlefs/**'
      - 'lib/CMSIS_6'
      - 'lib/mcuboot'
      - 'lib/oofatfs/**'
      - 'lib/uzlib/**'
      - 'lib/stm32lib'
      - 'ports/stm32/**'
      - 'ports/unix/variants/mcuboot*/**'
      - 'py/mpconfig.h'
      - 'shared/mcuboot/**'
      - 'shared/tinyusb/mboot/**'
      - 'tests/mcuboot/**'
      - 'tools/ci.sh'
      - 'tools/mcuboot_*.py'
      - 'tools/pydfu.py'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  host_tests:
    strategy:
      fail-fast: false
      matrix:
        ci_func:  # names are functions in ci.sh
          - mcuboot_python_test
          - mcuboot_mboot_test
          - mcuboot_host_core_test
          - mcuboot_host_bootloader_test
          - mcuboot_host_sweep_test
          - mcuboot_fuzz_test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Install packages
      run: tools/ci.sh mcuboot_setup
    - name: Run ci_${{ matrix.ci_func }}
      run: tools/ci.sh ${{ matrix.ci_func }}

  unix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Install packages
      run: tools/ci.sh mcuboot_setup
    - name: Build
      run: tools/ci.sh mcuboot_unix_build
    - name: Run tests
      run: tools/ci.sh mcuboot_unix_run_tests
    - name: Print failures
      if: failure()
      run: tests/run-tests.py --print-failures

  stm32:
    strategy:
      fail-fast: false
      matrix:
        ci_func:  # names are functions in ci.sh
          - mcuboot_stm32_bootloader_build
          - mcuboot_stm32_app_build
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v7
    - name: Install packages
      run: tools/ci.sh stm32_setup mcuboot_setup && tools/ci.sh stm32_path >> $GITHUB_PATH
    - name: Build ci_${{ matrix.ci_func }}
      run: tools/ci.sh ${{ matrix.ci_func }}
